### ISSUE TITLE
can't complete with compan-sourcekit

### ISSUE THREAD

**Issue by smallzhan** [terhechte/SourceKittenDaemon#22]
neither sourcekitdaemon.pkg nor installation by sourcecode works for me. the error in sourcekitdaemon console is:
 
>[HTTP] GET /complete X-Offset:458 X-Path:/var/folders/ks/2vgs8qvj1rb690pp6d2zs7ww0000gn/T/sourcekitten230196aG
dyld: lazy symbol binding failed: Symbol not found: __TFV21SourceKittenFramework4FileCfMS0_FT4pathSS_GSqS0__
 Referenced from: /usr/local/bin/sourcekittendaemon
 Expected in: /usr/local/bin/../Frameworks/SourceKittenFramework.framework/SourceKittenFramework

**Comment by nathankot** [comment]
Hey, what is the output of `ls /usr/local/bin/Frameworks` for you?

**Comment by smallzhan** [comment]
sorry, I've found the problem just now...
the `sourcekitten` installed from brew has version 0.7.x where the version bundled with sourcekittendaemon is 0.6.2. 

The problem disappeared with the uninstallation of sourcekitten from brew.

**Comment by nathankot** [comment]
Awesome! thanks for the update.

Closing, but just going to note that it's a little bit weird that the executable is searching `../Frameworks` as opposed to `../lib/SourceKittenDaemon.Frameworks` as referenced [here]( https://github.com/terhechte/SourceKittenDaemon/blob/7f0dc762026445ef6b443b61ed310c014a96119e/Makefile#L31).
