### ISSUE TITLE
Failed to load Addressbook

### ISSUE THREAD

**Issue by wangii** [terhechte/SourceKittenDaemon#24]
Got this error when building from source, and running with binary release:

Failed to load Addressbook class CNContactNameFormatter

How to fix it? thanks

**Comment by keith** [comment]
This is unrelated to SourceKittenDaemon. I'm seeing this error for all command line builds I do.

**Comment by nathankot** [comment]
Unrelated, quick google turns up: https://forums.developer.apple.com/thread/11792

Seems to be a solution:

> I'm posting an edited version of seancook's solution here because many people in a similar thread >?> found it works:
> 
> I noticed a message in Console.app along the lines of the Simulator runtime not being code signed. I went to the path it described "/Library/Developer/CoreSimulator/Profiles/Runtimes" and removed the runtimes that I had there. They were old runtimes, so I assume that some check in Xcode now applies that didn't previously.
>
> I then went into the Simulator's Hardware > Devices > Manage Devices menu and added a new iOS9 device. It didn't seem to do anything, so I quit out of Xcode and Simulator.app. I then re-started Simulator.app (via Xcode > ODT > Simulator) and lo and behold the expected iOS9 simulators were displayed.
>
> I closed and re-opened Xcode, changed the target OS for my project, and the Sims were finally displayed as run targets.
