### ISSUE TITLE
Special symbols like © seem to mess with sourcekit results

### ISSUE THREAD

**Issue by nathankot** [terhechte/SourceKittenDaemon#42]
As per what @galeo discovered in nathankot/company-sourcekit#16, I'll post my findings here:

Completion without the copyright symbol, offset is at: `CGRect(|)`:

```sh
$ sourcekitten complete --text '# ; import AVFoundation; CGRect()' --offset 32 | head
```

```json
[{
  "sourcetext" : "origin: <#T##CGPoint#>, size: <#T##CGSize#>"
}, ... ]
```

Completion with the copyright symbol, offset is at `CGRect(|)`:

```sh
$ sourcekitten complete --text '# ©; import AVFoundation; CGRect()' --offset 33 | head
```

```json
[{
  "sourcetext" : "()",
}, ... ]
```

Completion with the copyright symbol, offset is (seemingly) incorrect at `CGRect()|`:

```sh
$ sourcekitten complete --text '# ©; import AVFoundation; CGRect()' --offset 34 | head
```

```json
[{
  "sourcetext" : "origin: <#T##CGPoint#>, size: <#T##CGSize#>",
}, ... ]
```

It looks like xcode isn't considering the `©` character at all.

I'm not sure if this is desired behavior on Soucekit's part, but it'd be interesting to get your input guys @terhechte @seanfarley

**Comment by terhechte** [comment]
I wonder if this also applies to other characters or if this is a special case with only the © symbol.

**Comment by nathankot** [comment]
Most likely applies to others as well

**Comment by terhechte** [comment]
Does it only happen if it is in the same line? Or also if it is somewhere before the current cursor? To remedy this, we'd probably need to open the file, jump to the correct offset, and go back to make sure that none of those special characters are in there, right?

**Comment by seanfarley** [comment]
I imagine this is due to unicode since some unicode characters count as more than one. That's a bit hand wavy, I realize, but if sourcekit is expecting a byte string (warning: this is just a guess), then the counting will be off with unicode. You can see this in python2:

```bash
$ python2.7 -c 'print len("😈")
4
```

In the case of "©", we can see why adding `1` seemingly works:

```bash
$ python2.7 -c 'print len("©")'
2
```

**Comment by nathankot** [comment]
Nice :) I propose we fix this in either sourcekittendaemon or sourcekitten:

```swift
  7> "©".utf8.count
$R2: Distance = 2
  8> "©".characters.count
$R3: Distance = 1
```

**Comment by nathankot** [comment]
Actually, now that I think about it this really has to be fixed in the editor integrations doesn't it, otherwise the top layers would be needing to do magic translating a character offset to a utf8 offset.

**Comment by nathankot** [comment]
In emacs:

```elisp
(position-bytes (point))
```

**Comment by nathankot** [comment]
This has been fixed in company-sourcekit :) I'll add a note to the readme for sourcekittendaemon and close this.

**Comment by seanfarley** [comment]
👍
