### ISSUE TITLE
"Could not parse project" error

### ISSUE THREAD

**Issue by jakecraige** [terhechte/SourceKittenDaemon#47]
I'm trying to start up the daemon on a project with multiple `.xcodeproj`s at the root and it seems to be erroring out, saying the `xcodebuild` needs the `-project` option.

I ran `xcodebuild` with that option to make sure it wasn't a problem there and that seemed to run correctly. 

![1__tmux](https://cloud.githubusercontent.com/assets/3799709/16807425/308b2940-48cd-11e6-84dd-ae929ba1d4f2.png)

Any ideas for how to resolve this?

**Comment by terhechte** [comment]
This was fixed with Swift 3, I think.
