### ISSUE TITLE
Migrate to Xcode 8.0.

### ISSUE THREAD

**Issue by mitsuse** [terhechte/SourceKittenDaemon#49]
I tried to send a pull-req for migration to Xcode 8.0, but [Talyor](https://github.com/izqui/Taylor) is not developed actively.
What should be done?

**Comment by nathankot** [comment]
Hey @mitsuse I still haven't upgrade to Xcode 8.0 (hesitant,) so won't be able to look into this until then - is it possible to use Swift 2.3 frameworks in a Swift 3 project? I would have imagined it was possible and that we shouldn't need to do anything apart from get Taylor onto Swift 2.3 tell Carthage it's a Swift 2.3 dependency somehow?

**Comment by mitsuse** [comment]
@nathankot 

There is no binary-compatibility between Swift 2.x and 3.x.

> First, Swift 2.3 and Swift 3 are not binary compatible so your app's entire code base needs to pick one version of Swift.
>
> https://developer.apple.com/swift/blog/?id=36

Hmm, reconsidering to migration, there seems to be almost no advantage for the present...
We should wait for SourceKitten to migrates to Swift 3 and replace Taylor with other library.

SourceKitten will migrate to Swift 3 from [the next release][sourcekitten-0.14.1].

[sourcekitten-0.14.1]: https://github.com/jpsim/SourceKitten/releases/tag/0.14.1

**Comment by nathankot** [comment]
@mitsuse 

I agree regards to waiting for SourceKitten, in terms of Taylor we could simply do the migration ourselves. I've only just upgrade to Xcode 8 so getting familiar with the nuances there. Although (thankfully) SourceKittenDaemon works perfectly fine with Xcode 8 for me.

**Comment by terhechte** [comment]
I can close this ticket, right?
