### ISSUE TITLE
enhancement - support for visual studio code.

### ISSUE THREAD

**Issue by johndpope** [terhechte/SourceKittenDaemon#56]

**Comment by terhechte** [comment]
I'd love to switch the API to Language Server: https://github.com/Microsoft/language-server-protocol See:
https://github.com/terhechte/SourceKittenDaemon/issues/59

If you're interested, have a go at it. Otherwise I'd probably try to tackle this once #55 is done.

**Comment by johndpope** [comment]
hi @terhechte / got my plate full with other stuff at the moment.
this maybe a short cut cherry picking this code
https://github.com/RLovelett/vscode-swift

**Comment by johndpope** [comment]
fyi @terhechte  - https://github.com/RLovelett/langserver-swift
