### ISSUE TITLE
I get completions after remove `preprocessorFlags`

### ISSUE THREAD

**Issue by dengcqw** [terhechte/SourceKittenDaemon#65]
after remove this line, completion done  [//compilerArgs = compilerArgs + preprocessorFlags](https://github.com/terhechte/SourceKittenDaemon/blob/master/Sources/SourceKittenDaemon/Completer/Completer.swift#L84  )

just report this condition, if any one meet this problem.
PS:  if you are use  **sourcekittendaemon.vim**  check this issues https://github.com/keith/sourcekittendaemon.vim/issues/3

Finally, I can complete swift in vim.  Thx.

**Comment by huos3203** [comment]
@dengcqw 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  2 2017 08:30:37)
osx 10.13
1. install [SourceKittenDaemon](https://github.com/jpsim/SourceKitten/releases)
2. install `sourcekittendaemon.vim` by vim-plug
3. start Daemon
```
SourceKittenDaemon start  --project /private/tmp/abcde/my.xcodeproj
```
4. `/ping`  return 'OK'

but  it not work, when i run the command `vim file.swift` . file.swift from `/files`
