### ISSUE TITLE
Makefile not working?

### ISSUE THREAD

**Issue by jamesshapiro** [terhechte/SourceKittenDaemon#67]
I'm probably doing something dumb, but running "make install" from the directory SourceKittenDaemon produces the following error: 

> make: *** No rule to make target `.build/release/sourcekittend', needed by `dist/bin/sourcekittendaemon'.  Stop.

Running on Mac OSX 10.11.6

**Comment by callo90** [comment]
same issue

**Comment by callo90** [comment]
same issue here

**Comment by nathankot** [comment]
@jamesshapiro @callo90 my bad should have tested the `Makefile` on a clean directory, I'll push a fix.

**Comment by callo90** [comment]
now getting this during compiling 

```install_name_tool -change /Users/SourceKittenDaemon-master/.build/release/libCLibreSSL.dylib  /usr/local/lib/libCLibreSSL.dylib dist/bin/sourcekittendaemon
make: *** No rule to make target `dist/lib/libCYaml.dylib', needed by `dist'.  Stop.```

**Comment by jamesshapiro** [comment]
Same issue for me:

make: *** No rule to make target `dist/lib/libCYaml.dylib', needed by `dist'.  Stop.

Running make install again does not produce any errors, but I'm not sure if that fixes the problem. Have not tested yet.

**Comment by nathankot** [comment]
@callo90 @jamesshapiro ugh sorry for the back and forth guys, please try ccb06ae :)

**Comment by N4tr0n** [comment]
Cloned the repo, ran `make install` and this error occurred:
`make: *** No rule to make target 'dist', needed by 'install'.  Stop.`
I took a look at ccb06ae and it does seem like the `dist` rule got deleted.

**Comment by nathankot** [comment]
Eeek thanks @N4tr0n I completely neglected the `make install` target, just pushed 574c7a7
