### ISSUE TITLE
SKD requires xcodeproj, but Swift can be used outside of Xcode

### ISSUE THREAD

**Issue by troyibm** [terhechte/SourceKittenDaemon#70]
Swift can be used for sever side coding now (via openwhisk for instance).  I'd like to use Atom and the swift plugins (language-swift, swift-debugger, autocomplete-swift) for this instead of using Xcode but I see from the code (haven't really tried this - still just investigating) that without a .xcodeproj file, then SourceKittenDaemon won't start.

How can I get autocomplete into this example: https://medium.com/@Aciid/hacking-atom-to-create-a-swift-ide-that-runs-on-linux-and-mac-c7d9520a0fac ?  Thanks.

**Comment by johndpope** [comment]
fyi - https://github.com/RLovelett/langserver-swift

**Comment by felix91gr** [comment]
Alternatively, you can actually generate the XcodeProj file [natively from the Swift Package Manager](https://stackoverflow.com/questions/34116041/when-using-swift-package-manager-how-can-i-generate-an-xcode-project-file-for-de#36579682) :)

**Comment by troyibm** [comment]
@felix91gr if an xcodeproj file is created but the editor being used isn't Xcode, will it be updated with an editor like Atom as more swift code is written??

**Comment by terhechte** [comment]
@troyibm If you add new Swift files to the project, you have to re-generate the Xcode file with SPM.

**Comment by troyibm** [comment]
what happens if you modify a Swift file (like add a function or something), will auto-complete show that function without re-generating the xcodeproj file?

**Comment by felix91gr** [comment]
It should, I'm almost certain. Did it work for you? Sorry for the late answer. I'm doing cleanup and I just realized that this was left unsolved.

**Comment by troyibm** [comment]
Thanks for the late answer.  It's a timely answer.  I'm starting a swift-as-the-server project this week.  I didn't try it, but likely will soon.  Thanks.  You can close and I'll reopen if there is a problem.

**Comment by felix91gr** [comment]
Awesome :)

I hope
