### ISSUE TITLE
Cant install on Linux swift tool version for FileSystemWatcher is old

### ISSUE THREAD

**Issue by mikebgrep** [terhechte/SourceKittenDaemon#81]
I can't install it on Linux this package is using old swift tool version is have some another way to install it
```
#if os(Linux)
package.dependencies.append(.Package(url: "https://github.com/felix91gr/FileSystemWatcher.git",
        majorVersion: 1))
#endif
```

**Comment by terhechte** [comment]
Hey, not that I'd know of. It might be reasonably easy to use a different File watcher library (something that is newer or maintained and works on Linux). However, there're a couple other Swift LSP Libraries, some of which might work out of the box. I'm not using Swift on Linux, so I don't have much knowledge here:

- https://github.com/ChimeHQ/SwiftLSPClient
- Apples Official One: https://github.com/apple/sourcekit-lsp

If you're using vscode on Linux, then there's a semi official library from the Swift Server Work Group:
- https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang

There's also this one which advertises Linux support:
https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swift-development-environment

**Comment by mikebgrep** [comment]
@terhechte Thank you for your answer, I will give a chance to vscode.
